/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    java
    `maven-publish`
    //id("org.openjfx.javafxplugin") version "0.0.13"
    id("com.github.johnrengelman.shadow") version "7.1.2"
    kotlin("jvm") version "1.7.20"
    kotlin("plugin.serialization") version "1.7.20"
}

//javafx {
//    version = "17.0.5"
//    modules = listOf("javafx.controls", "javafx.*")
//}

repositories {
    //mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    implementation("com.google.code.gson:gson:2.10")
    implementation("org.apache.commons:commons-lang3:3.12.0")
    implementation("net.java.dev.jna:jna-platform:5.12.1")
    implementation("com.formdev:flatlaf:2.6") //    implementation("com.formdev:flatlaf:0.45")
    implementation("com.intellij:forms_rt:7.0.3")
    implementation("commons-cli:commons-cli:1.5.0")
    implementation("com.github.seancfoley:ipaddress:5.3.4")
    implementation("org.apache.logging.log4j:log4j-core:2.19.0")
    implementation("org.apache.httpcomponents:httpclient:4.5.13")


    implementation("org.jetbrains.kotlinx:kotlinx-cli:0.3.5")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1")
}

group = "me.reply.qubo"
version = "0.4"
description = "quboscanner"
java.sourceCompatibility = JavaVersion.VERSION_17

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.jar {
    manifest {
        attributes(
            "Main-Class" to "me.replydev.qubo.Main"
        )
    }
}